-- =============================================================================
-- commit_order_with_lines — atomic INSERT for the order row + its
-- order_items in a single transaction.
--
-- Background:
--   placeOrder used to do:
--     1. INSERT INTO orders         (own HTTP round-trip, own txn)
--     2. INSERT INTO order_items    (own HTTP round-trip, own txn)
--     3. UPDATE cart_checkout_sessions
--
--   If step 2 failed after step 1 succeeded, the orphan order row had
--   to be DELETEd by compensating JS — and if THAT delete failed, the
--   row was stuck in the DB with no items, blocking the customer's
--   next checkout attempt while inventory stayed reserved.
--
-- This function:
--   - Inserts the order row + all order_items in a single PG transaction
--   - On any line failure, the order insert is rolled back automatically
--     (no compensating DELETE needed; Postgres handles it)
--   - Returns the order id + order_number so the caller has what it
--     needs for the cart_checkout_sessions update + email send below
--
-- Step 3 (cart_checkout_sessions update) stays in the JS action — it's
-- a non-critical UPDATE that, if it fails, leaves the soft session in
-- 'soft' state until the reaper sweeps it. The order is already
-- committed; the session-state cleanup is best-effort.
--
-- Permission gate: callers use createAdminClient() which bypasses RLS,
-- so the function doesn't repeat the auth/permission check that the
-- placeOrder action already enforced. Defined SECURITY DEFINER for
-- consistency with other commit RPCs in this codebase.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.commit_order_with_lines(
  p_order jsonb,
  p_lines jsonb
)
RETURNS TABLE(order_id uuid, order_number text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order_id uuid;
  v_order_number text;
BEGIN
  -- Insert the order. order_number autogenerated by column default.
  --
  -- The jsonb_populate_record pattern lets the caller pass a flat
  -- object and we hydrate every matching column without listing each
  -- one here — keeps this function stable across additive schema
  -- changes to public.orders.
  INSERT INTO public.orders
  SELECT * FROM jsonb_populate_record(NULL::public.orders, p_order)
  RETURNING id, order_number INTO v_order_id, v_order_number;

  -- Bulk insert the lines. We rebuild the jsonb array with order_id
  -- forced on each element (whatever the caller passed is overwritten)
  -- then hydrate into the order_items shape via populate_recordset.
  -- If any line is invalid (e.g. variant_id FK violation, malformed
  -- attribute_combo, line totals tripping a CHECK constraint), the
  -- whole transaction rolls back — including the order row above.
  INSERT INTO public.order_items
  SELECT * FROM jsonb_populate_recordset(
    NULL::public.order_items,
    (SELECT jsonb_agg(elem || jsonb_build_object('order_id', v_order_id))
     FROM jsonb_array_elements(p_lines) elem)
  );

  RETURN QUERY SELECT v_order_id, v_order_number;
END;
$$;

COMMENT ON FUNCTION public.commit_order_with_lines(jsonb, jsonb) IS
'Atomic commit of an orders row + its order_items rows in a single transaction. Used by placeOrder to eliminate the partial-commit window between the two inserts. The caller is responsible for the post-commit cart_checkout_sessions update + email send (those are best-effort and safe to retry separately).';

NOTIFY pgrst, 'reload schema';
